s

diff --git a/git/hooks/ensure-newline b/git/hooks/ensure-newline
--- a/git/hooks/ensure-newline
+++ b/git/hooks/ensure-newline
@@ -3,14 +3,19 @@
 # ステージされた追加/変更ファイル一覧を取得
 files=$(git diff --cached --name-only --diff-filter=AM)
 
+# textfmt がなければ exit
+if ! command -v textfmt &>/dev/null; then
+    echo "textfmt could not be found"
+    echo "go install github.com/naoyafurudono/textfmt@latest"
+    exit 1
+fi
+
 # 末尾改行を補完する処理
 for f in $files; do
-    if [ -f "$f" ] && git grep -Iq . -- "$f"; then  # テキストファイルのみ対象
-        if [ "$(tail -c1 "$f")" != "" ] && [ "$(tail -c1 "$f")" != $'\n' ]; then
-            echo >> "$f"      # 末尾に改行を追加
-            git add "$f"      # 修正をステージに追加
-        fi
+    if [ -f "$f" ] && git grep -Iq . -- "$f"; then # テキストファイルのみ対象
+        textfmt "$f"
+        git add "$f" # 修正をステージに追加
     fi
 done
 
-exit 0  # 通常のコミット続行
+exit 0 # 通常のコミット続行
